### ISSUE TITLE
Admin assets enqueue on all screens

### ISSUE THREAD

**Issue by aaemnnosttv** [moderntribe/tribe-common#344]
![image](https://cloud.githubusercontent.com/assets/1621608/23793554/83890156-0594-11e7-8bb9-41955e0603b5.png)
> Screenshot of fresh WP install (4.7.3) with Event Tickets 4.4.4. The same goes for The Events Calendar 4.4.4 as well.

I noticed recently that some Tribe assets were loading on screens that they should not be.

After digging into the code a bit, it seems that the assets are registered with a callback as a `filter` to control whether or not they should be enqueued: https://github.com/moderntribe/tribe-common/blob/67f2b769702d759a22461e590b8bd13ef3a53b85/src/Tribe/Main.php#L216

This is referenced in `Tribe__Assets` here: https://github.com/moderntribe/tribe-common/blob/67f2b769702d759a22461e590b8bd13ef3a53b85/src/Tribe/Assets.php#L133-L141
```php
/**
 * Allows developers to hook-in and prevent an asset from been loaded
 *
 * Note: When you pass callables on the `$asset->filter` argument this will be hooked here
 *
 * @param bool   $enqueue If we should enqueue or not a given asset
 * @param object $asset   Which asset we are dealing with
 */
$enqueue = apply_filters( 'tribe_asset_enqueue_' . $asset->slug, $enqueue, $asset );
```

This filter callback however does not appear to ever be hooked, and so it goes on and enqueues it on all admin screens.

**Comment by barryhughes** [comment]
Hi @aaemnnosttv,

Thanks for highlighting this! It does look like some of our code and inline documentation has fallen out of date following [this change](https://github.com/moderntribe/tribe-common/commit/8385d75a5adbc4fbc562a47b327e810fab47052c). Notes:

* Any time an asset is registered, it needs to provide conditional callbacks via a `'conditionals'` array (within the arguments array), as `'filter'` [(example here)](https://github.com/moderntribe/tribe-common/blob/67f2b769702d759a22461e590b8bd13ef3a53b85/src/Tribe/Main.php#L216) is no longer supported
* The information about use of `$asset->filter` [provided in this docblock](https://github.com/moderntribe/tribe-common/blob/67f2b769702d759a22461e590b8bd13ef3a53b85/src/Tribe/Assets.php#L133-L141) probably ought to be removed at this point - that property won't exist and the hook is no longer used for that purpose

For our own ref, this has been logged as [#75031](https://central.tri.be/issues/75031).

Thanks again, Evan!

**Comment by barryhughes** [comment]
Just a quick note that - in line with our other repos - we're going to close the issue tracker here. Again, thanks for flagging this issue (which is now logged on our internal tracker).
